FROM r-base

RUN mkdir -p /opt/services/shinyapp/src
WORKDIR /opt/services/shinyapp/src/

RUN R -e "install.packages('shiny', repos='https://cran.rstudio.com/')"

COPY . /opt/services/shinyapp/src

EXPOSE 8100
CMD R -e "shiny::runApp(appDir='shinyapp', port=8100, host='0.0.0.0')"

LABEL author="Timothée Mazzucotelli <mazzucot@igbmc.fr>"
LABEL maintainer="Timothée Mazzucotelli <mazzucot@igbmc.fr>"
